name: AI Automated pipeline (c2)

on:
  workflow_dispatch:
    inputs:
      model:
        description: "model to use for training <linear/xgboost>"
        required: true
        default: "xgboost"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install python dependencies
      working-directory: ./challenge2
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute main script
      working-directory: ./challenge2/src
      run: |
        python main.py ${{ github.event.inputs.model}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pipeline_artifacts
        path: |
            challenge2/src/Logs
            challenge2/src/Models

